# Generated by Django 5.0.7 on 2024-08-08 06:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='your first name')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='your last name')),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.IntegerField(default=1234567890)),
                ('address', models.CharField(choices=[('ktm', 'Kathmandu'), ('lat', 'Lalitpur'), ('bat', 'Bhaktapur')], default='ktm', max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll',
            new_name='roll_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='John', max_length=100, null=True, verbose_name='your first name'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100, null=True, verbose_name='your last name'),
        ),
        migrations.CreateModel(
            name='StudentFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=30)),
                ('class_room', models.CharField(max_length=30)),
                ('today_day', models.DateTimeField(auto_now_add=True)),
                ('class_timing', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_faculties', to='page.student')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_faculties', to='page.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', through='page.StudentFaculty', to='page.teacher'),
        ),
        migrations.CreateModel(
            name='SubjectMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='page.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
