# Generated by Django 5.0.7 on 2024-07-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollin', '0004_remove_student_relation_student_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_rollno',
            field=models.IntegerField(default=1),
        ),
    ]
