# Generated by Django 5.0.7 on 2024-08-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollin', '0008_subject_subject_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(default='Section-1', max_length=50),
        ),
    ]
