# Generated by Django 5.0.7 on 2024-07-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(choices=[('ktm', 'kathmandu'), ('lat', 'lalitpur'), ('bat', 'bhatapur')], default='ktm', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=1234567890),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
