# Generated by Django 5.0.7 on 2024-07-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollin', '0003_student_studentfaculty_teacher_delete_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='relation',
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', through='enrollin.StudentFaculty', to='enrollin.teacher'),
        ),
        migrations.AddField(
            model_name='studentfaculty',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_faculties', to='enrollin.teacher'),
        ),
        migrations.AlterField(
            model_name='studentfaculty',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_faculties', to='enrollin.student'),
        ),
    ]
