# Generated by Django 5.0.7 on 2024-07-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollin', '0005_student_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Student_age',
            field=models.IntegerField(default=18),
        ),
    ]
