# Generated by Django 5.0.7 on 2024-08-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollin', '0009_teacher_passby'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='passby',
            field=models.CharField(default='section1', max_length=40),
        ),
    ]
